# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MasonX-Interp-WithCallbacks
version:      1.11
version_from: lib/MasonX/Interp/WithCallbacks.pm
installdirs:  site
requires:
    Class::Container:              0.09
    HTML::Mason:                   1.23
    Params::CallbackRequest:       1.11
    Test::Simple:                  0.17

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
