---
name: MasonX-Interp-WithCallbacks
version: 1.18
author:
  - 'David Wheeler <david@kineticode.com>'
abstract: Mason callback support via Params::CallbackRequest.
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.2701
requires:
  Class::Container: 0.09
  HTML::Mason: 1.23
  Params::CallbackRequest: 1.15
  Test::Simple: 0.17
build_requires:
  Test::More: 0.17
recommends:
  Apache::TestMB: 0
  Test::Pod: 1.20
provides:
  MasonX::Interp::WithCallbacks:
    file: lib/MasonX/Interp/WithCallbacks.pm
    version: 1.18
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
